SELECT ROUND(COST) FROM PETRESCUE;

SELECT LENGTH(ANIMAL) FROM PETRESCUE;

SELECT UCASE(ANIMAL) FROM PETRESCUE;

SELECT DISTINCT (UCASE(ANIMAL)) FROM PETRESCUE;

SELECT * FROM PETRESCUE
	WHERE LCASE(ANIMAL)='cat';