SELECT EMP_ID, F_NAME, L_NAME, SALARY 
FROM EMPLOYEES 
WHERE SALARY<(SELECT AVG(SALARY)
				FROM EMPLOYEES);
				
SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY 
FROM EMPLOYEES;

select * from ( select EMP_ID, F_NAME, L_NAME, DEP_ID from employees) AS EMP4ALL;