Create Table PETSALE (
	ID INT NOT NULL,
	PET CHAR(20),
	SALEPRICE DECIMAL(6,2),
	PROFIT DECIMAL(6,2),
	SALEDATE DATE
	);
	
	CREATE TABLE PET (
		ID INT NOT NULL,
		ANIMAL VARCHAR(20),
		QUANTITY INT 
		);