select SC.NAME_OF_SCHOOL,SC.COMMUNITY_AREA_NAME, SC.AVERAGE_STUDENT_ATTENDANCE 
from SCHOOLS as SC 
LEFT OUTER JOIN CHICAGO_CENSUS_DATA as CE 
on SC.COMMUNITY_AREA_NUMBER=CE.COMMUNITY_AREA_NUMBER 
where CE.HARDSHIP_INDEX = 98;