select CR.CASE_NUMBER, CR.COMMUNITY_AREA_NUMBER
from CHICAGO_CRIME_DATA as CR 
FULL OUTER JOIN CHICAGO_CENSUS_DATA as CE 
on CR.COMMUNITY_AREA_NUMBER=CE.COMMUNITY_AREA_NUMBER 
WHERE (CE.COMMUNITY_AREA_NAME = 'Oakland') 
OR (CE.COMMUNITY_AREA_NAME = 'Armour Square') 
OR (CE.COMMUNITY_AREA_NAME = 'Edgewater') 
OR (CE.COMMUNITY_AREA_NAME = 'Chicago');