--#SET TERMINATOR @
CREATE PROCEDURE UPDATE_SALEPRICE (
	IN ANIMAL_ID INTEGER, IN ANIMAL_HEALTH VARCHAR(5))

LANGUAGE SQL
MODIFIES SQL DATA

BEGIN

	IF ANIMAL_HEALTH = 'BAD' THEN
		UPDATE PETSALE
		SET SALEPRICE = SALEPRICE -(SALEPRICE * 0.25)
		WHERE ID = ANIMAL_ID;
	
	ELSEIF ANIMAL_HEALTH = 'WORSE' THEN 
	UPDATE PETSALE
	SET SALEPRICE = SALEPRICE - (SALEPRICE * 0.5)
	WHERE ID = ANIMAL_ID;
	
	ELSE UPDATE PETSALE
	SET SALEPRICE = SALEPRICE
	WHERE ID = ANIMAL_ID;
	
	END IF;
	
END 
@